---
# tasks file for basic setup
  

# disable SElinux, disable firewalld and restart system

- name: Ensure that the selinux packages are installed
  tags: selinux
  become: True
  yum:
     name: "{{ item }}"
     state: present
  register: selinux_yum
  with_items:
    - libselinux-python
    - selinux-policy


- name: Applying selinux policy and state configurations
  tags: selinux
  become: True
  selinux:
    conf: "{{ selinux_conf }}"
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_state }}"
  when: selinux_yum is success


- name: Stop firewalld
  service: name=firewalld state=stopped


- name: Disable firewalld
  service: name=firewalld enabled=no


- name: Stop NetworkManager
  service: name=NetworkManager  state=stopped


- name: Disable NetworkManager
  service: name=NetworkManager  enabled=no


# timedatectl

- name: Set timezone to Europe/Kiev
  become: True
  timezone:
    name: Europe/Kiev


# basic soft

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest


- name: Install basic software
  become: True
  yum: name={{ item }} state=installed update_cache=yes 
  with_items:
     - vim
     - mc
     - net-tools
     - bind-utils
     - epel-release
     - tree
     - wget
     - unzip
     - iptables-services


# change hostname and restart system

- name: Change hostname
  hostname:
    name: "{{ new_hostname }}"
  register: "hostname_status"
  become: true
  when: ansible_hostname != new_hostname
  notify: Restart Operation System



...

